name: 215a
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python
  - pytorch
  - pip:
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - scikit-learn
    - jupyterlab
    - torch
    - torchvision
    - torchaudio
    - ipykernel
    - ipython
    - notebook
    - imblearn
    - tabpfn
